name: intraop
channels:
  - conda-forge
dependencies:
  - python=3.11
  - montreal-forced-aligner=3.1.1
  - joblib=1.2.0
  - mne
  - mne-bids
  - numpy
  - scipy
  - matplotlib
  - h5py
  - pip
  - pip:
      - noisereduce
      - textgrid
      - hydra-core