name: spike_band

extractor:
  # _target_: preprocessing.utils.feature_extraction.extract_band
  _target_: utils.feature_extraction.extract_band

  frange: [300, 1000]
  power: abs
  smooth_ms: 25

  method: iir
  iir_params:
    order: 4
    ftype: butter

out_fs: 200